let marks = [91, 82, 63, 85, false, "Not Present"];
console.log(marks[0]);
console.log(marks[1]);
console.log(marks[2]);
console.log(marks[3]);
console.log(marks[4]);
console.log(marks[5]);
console.log(marks[6]);
console.log("The length of marks is", marks.length);
marks[6] = 89;
marks[0] = 98;
console.log("The length of marks is", marks.length);
console.log(marks);